### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by eric-figueira** [eric-figueira/pizzahub#1]
- [x] Consider ENUM in parameters and fixed types, such as roles, forma_pagamento, status_pedido
- [ ] Use Public ID (UUID or Slug) + Identity
- [x] Add utility to contain Regex
- [x] Use lombok for setters + Validations on DTOs
- [x] Consider dividing controllers into sub-files
- [x] Solid + Clean Architecture files folders
- [x] Padronize ResponseEntity return in controllers
- [ ] Separate concerns in controller (create Services, which will in fact access repositories, leaving parameter validations to controller)
- [ ] Improve response and exceptions error messages
- [x] Replace optionalEntity by orElseThrow statement
- [x] Refactor update methods in controllers. Make them less verbouses
- [ ] Create proper Mappers
- [x] Consider remove some DTOs
- [ ] Implement API Logs
- [ ] Remove elses
- [ ] Add proper throw Exceptions
- [x] Consider changing enums such as PaymentMethod and Role to entities
- [ ] Add swagger documentation
- [ ] Find a way to make partial updates easily
- [ ] Create embedded Address class
- [ ] Add updatedAt, hiredAt, firedAt
