### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by eric-figueira** [eric-figueira/pizzahub#2]
- [ ] Fix menu item controller
- [ ] Fix pagination parameters errors (they are not optional right now, and must fix the perPage verification)
- [ ] Change Identity to UUID in every part
